name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  set-env:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up the .env file
      run: |
        echo "TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
        echo "HIGHLIGHT_CHANNEL_ID=${{ secrets.HIGHLIGHT_CHANNEL_ID }}" >> .env
  build:
    runs-on: self-hosted
    needs: set-env
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        npm run build
        docker build . -t inversify-discord-bot:latest
  run:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Run the Docker image
      run: docker run -itd inversify-discord-bot:latest
