name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up the .env file
      run: |
        echo "TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
        echo "HIGHLIGHT_CHANNEL_ID=${{ secrets.HIGHLIGHT_CHANNEL_ID }}" >> .env
    - name: npm install dependencies
      run: npm i
    - name: npm build and test
      run: npm run build

  docker-build:
    runs-on: self-hosted
    needs: install
    steps:
    - name: Build the Docker image
      run: docker build . -t inversify-discord-bot:latest

  docker-run:
    runs-on: self-hosted
    needs: docker-build
    steps:
    - name: Run the Docker image
      run: docker run -itd inversify-discord-bot:latest
