name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag inversify-discord-bot:$IDB_TAG
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Run the Docker image
      run: docker run -itd inversify-discord-bot:$IDB_TAG
